# Generated by Django 3.0.5 on 2020-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_pics'),
        ),
    ]
