# Generated by Django 3.0.3 on 2020-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0004_auto_20200412_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(default='', max_length=4, verbose_name='Year of Publication'),
        ),
    ]
