# Generated by Django 3.0.3 on 2020-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0006_auto_20200413_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='First name of the Author', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Last name of the Author', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Upload cover photo of the book', upload_to='book_pics'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_name',
            field=models.CharField(help_text='Name of Publisher', max_length=200),
        ),
    ]
