# Generated by Django 3.0.3 on 2020-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0007_auto_20200413_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='noImage.jpg', help_text='Upload cover photo of the book', upload_to='book_pics'),
        ),
    ]
