# Generated by Django 3.0.3 on 2020-04-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0008_auto_20200413_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(help_text='Choose an instance of a book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_website.Book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(help_text='Published by [insert author name and] on [insert year of publication]', max_length=200),
        ),
    ]
