# Generated by Django 3.0.3 on 2020-04-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0009_auto_20200415_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(help_text='Follow this template: Published by [insert author name] on [insert year of publication]', max_length=200),
        ),
    ]
