# Generated by Django 3.0.3 on 2020-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0010_auto_20200415_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Follow this template: [YYYY-MM-DD] (Ex.: 2020-04-26', null=True),
        ),
    ]
