# Generated by Django 3.0.3 on 2020-04-14 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_website', '0012_auto_20200415_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='NOTE: PLEASE CHOOSE NULL FIELD IF THERE IS NO BORROWER', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Follow this template: [YYYY-MM-DD] (Ex.: 2020-04-26)   NOTE: PLEASE CHOOSE NULL FIELD IF THERE IS NO BORROWER', null=True),
        ),
    ]
