# Generated by Django 3.0.3 on 2020-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0013_auto_20200415_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Follow this template: [YYYY-MM-DD] (Ex.: 2020-04-26)   NOTE: PLEASE LEAVE FIELD AS EMPTY IF THERE IS NO BORROWER', null=True),
        ),
    ]
