# Generated by Django 3.0.3 on 2020-04-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0017_auto_20200419_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Upload cover photo of the book', upload_to='book_pics'),
        ),
    ]
