# Generated by Django 3.0.3 on 2020-04-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0019_auto_20200419_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
