# Generated by Django 3.0.3 on 2020-04-22 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_website', '0021_auto_20200423_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, help_text='[NOTE: PLEASE CHOOSE NULL FIELD IF THERE IS NO BORROWER]', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Follow this template: [YYYY-MM-DD] (Ex.: 2020-04-26) [NOTE: PLEASE LEAVE FIELD AS EMPTY IF THERE IS NO BORROWER]', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Book availability [NOTE: PLEASE SET TO AVAILABLE IF BOOK IS NOT BORROWED]', max_length=1),
        ),
    ]
