# Generated by Django 3.0.3 on 2020-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0022_auto_20200423_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dewey',
            field=models.CharField(default='', help_text='3 Digit Call Number based on Book Subject or Genre', max_length=3, verbose_name='Dewey Decimal System'),
        ),
    ]
