# Generated by Django 3.0.7 on 2020-06-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_website', '0030_historyofborrowers_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyofborrowers',
            name='bookInstance',
        ),
    ]
